keys:
  - &vanilla 2649340CC909F821D25167143750028ED04FA42E
  - &nixos-linode 64D0B35603A7C10BD470EE142365C886CC978135

creation_rules:
  - path_regex: ^[^/]*.yaml$

    key_groups:
      - pgp:
          - *vanilla
          - *nixos-linode
