# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  trojan-go = {
    pname = "trojan-go";
    version = "v0.10.6";
    src = fetchFromGitHub ({
      owner = "p4gefau1t";
      repo = "trojan-go";
      rev = "v0.10.6";
      fetchSubmodules = false;
      sha256 = "sha256-ZzIEKyLhHwYEWBfi6fHlCbkEImetEaRewbsHQEduB5Y=";
    });
  };
}
