# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  csgo_exporter = {
    pname = "csgo_exporter";
    version = "1.4.2";
    src = fetchFromGitHub ({
      owner = "kinduff";
      repo = "csgo_exporter";
      rev = "1.4.2";
      fetchSubmodules = false;
      sha256 = "sha256-DqcfBiXkQwsvcJPLXI9eNRWY4Wn4IOdnKX4XZzS7eKw=";
    });
  };
}
